# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6b638a6bdc4bafed30fd5be8bb7c78dc1157501779fd82ba755575672707f1fc092341e229df5bb98ffe8ef8fecf825b81dcdac062f60e5fec897cf33bdc785

test:
  secret_key_base: a271794b3a898d50a85867a13692b1d6f5f768b5bf9caca2d0f0357736dda4e0578418af355068a9691ef374a225c237b2b940e477e742a7a9f8828e3fa671b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
